import type { Metadata } from "next";
import { Montserrat, Playball } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const playball = Playball({
  weight: ["400"],
  variable: "--font-playball",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Catering Service",
  description: "Generated by create next app",
};

// TODO: Playball google font for title

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={false} data-arp="">
      <body className={`${montserrat.variable} ${playball.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
